name: PrivyPG

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DP_PORT}:5432'
    healthcheck:
      test: pg_isready -U ${DB_USER}
